CLI: remove 'android' sub-command
Attempting to use this command will fail with the following message:

    This command is deprecated as Android is moving to using the 'tools/bin/sdkmanager' script. Please update your scripts to use 'uno sdkmanager'

    ERROR: Android SDK Manager was not found at 'C:\Users\morten\AppData\Local\Android\sdk\SDK Manager.exe'. (pass --trace for stack trace)