C#: update GlobalAssemlyInfo logic
This generates similar logic to the current csprojs do, with one
exception: it only includes GlobalAssemblyInfo.targets if it
exists. This is so we don't have to generate a dummy-project to
test-compile inside the output-directory during
"scripts/build.sh --unocore".