Android: fix compile error
#211 came in with an extra '@' character, causing compile-time error.

    error: failed linking references.
    C:\Users\morten\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.1.aar\c7791c5f011e3ee28990f27611eb82c8\res\values\values.xml: AAPT: error: expected boolean but got (raw string) @'false'.